### ISSUE TITLE
Individual Major Donors Recipe Enhancements

### ISSUE THREAD

**Issue by allisonletts** [SFDO-Community-Sprints/Snowfakery-Recipe-Templates#107]
The original recipe (#93) was made during a sprint, and there were a few things they were still discussing/working on:

- [x] Add instructions for running the recipe multiple times (consensus was 100 times to get a reasonable distribution)
- [x] Use "Step" to round off the amounts on some of these [(Docs)](https://snowfakery.readthedocs.io/en/latest/index.html#random_number)
- [x] Add some Installments/pledges
- [x] More realistic tasks for the engagement plans
- [x] Use variables to handle min and max gift amounts

**Comment by nai888** [comment]
@allisonletts What is the purpose of defining the Opportunity Amounts with variables? Is it just to put that at the top of the recipe so it's easier to edit? Thanks!

**Comment by allisonletts** [comment]
@nai888 I didn't create the original, but yes, that's my assumption. Major Donors can cover so much territory, and putting the numbers in variables means that we can create an appropriately-sized major gift for the target org more easily.

**Comment by nai888** [comment]
This should now be completed once the PR is merged 😁

**Comment by programmer2coder** [comment]
This should have closed automatically when the PR merge happened.
