### ISSUE TITLE
Investigate International Accounts Recipe sometimes using US States

### ISSUE THREAD

**Issue by acrosman** [SFDO-Community-Sprints/Snowfakery-Recipe-Templates#14]
The international accounts recipe is great and creating people that match the locale settings from the provided list, but it seems to use US states when for French Canadian locale.  So you get addresses like these:

85284 Lapointe Heights
North Isabelle, California 21546
Canada

856 Dominique Overpass
Michelview, Oregon 66951
Canada

This may be a weakness of Fakery itself (falling back to US when it doesn't have anything for the locale), but we should investigate that and see if there is an easy solution.

**Comment by allisonletts** [comment]
Running tests now. In Faker, Canada is under en_CA not fr_CA, so I'm hoping that'll be the whole fix.
