### ISSUE TITLE
Adjust Opportunity Naming in OpportunitiesWithAllocations.yml

### ISSUE THREAD

**Issue by acrosman** [SFDO-Community-Sprints/Snowfakery-Recipe-Templates#15]
Right now the recipe name the Opps with hard coded values that are meant to make it easy to tell which is which.  That's great when checking the recipe itself and totally makes sense why we did it that way, but when using the recipe to create fake data as intended it leave the names in a strange state. Ideally they would either match NPSP default convention or allow NPSP to name the donations directly.

Example of current behavior:
`2 GAU (Random Amount) Opportunity for Melendez, Skinner and Flowers`

**Comment by allisonletts** [comment]
Working through this--opp naming defaults are not set automatically in the npsp:install_prod flow, and record types are also not created. I think some of this may be a documentation challenge, on top of any technical changes to the yaml file
