### ISSUE TITLE
Remove legacy syntax from NPSP Account recipe

### ISSUE THREAD

**Issue by jesslopez-sf** [SFDO-Community-Sprints/Snowfakery-Recipe-Templates#6]
https://github.com/SFDO-Community-Sprints/DataGenerationToolkit/blob/main/snowfakery_samples/npsp/Account_npsp.recipe.yml

- [ ] Remove legacy syntax (i.e. last_name and replace with more salesforce api-like values --LastName)

**Comment by programmer2coder** [comment]
Is this issue about removing legacy syntax from just that one recipe? (recipe now known as Account_npsp.recipe).  Wasn't that completed?  Or is it about the recipes in the NPSP folder in general?

**Comment by acrosman** [comment]
This one probably should be marked complete, and we should create several between now and the next sprint to flag specific recipes that need clean up
