### ISSUE TITLE
Bug: Oppty NPSP Soft Credit Recipe does not create OCRs

### ISSUE THREAD

**Issue by samanthashain** [SFDO-Community-Sprints/Snowfakery-Recipe-Templates#89]

**Comment by samanthashain** [comment]
This recipe could also be improved by creating some Closed Won opportunities (for use in Household NPSP Rollups)

**Comment by allisonletts** [comment]
https://github.com/SFDO-Community-Sprints/Snowfakery-Recipe-Templates/blob/847beccd3d746d693b4596b1fec2f01deaf4ec99/snowfakery_samples/npsp/Opportunity_npsp_soft_credit.recipe.yml

**Comment by allisonletts** [comment]
I just ran the recipe and I came up with five OCRs, as anticipated.
To make this recipe a little clearer, I'm going to modify it so that it creates one opp per contact, and then links them with an OCR--that way we won't have any contacts without OCRs.

**Comment by samanthashain** [comment]
Hmm I will pull this down and test again @allisonletts as time allows.  In my last run of the old version, I ended up with oppties sans OCRs which should also be fixed in your revamp.  My apologies if there was a different aspect of user error that motivated this ticket!  TYSM!
