### ISSUE TITLE
Corporate Donors Recipe

### ISSUE THREAD

**Issue by allisonletts** [SFDO-Community-Sprints/Snowfakery-Recipe-Templates#94]
Create a recipe that sets up corporate donor records. 

Expected objects: Accounts, Opportunities, mostly Pledges, spanning at least five years.
- [ ]  Create donor records
- [ ]  Create pledge records
- [ ]  Create payments
- [ ] Create contact affiliations
- [ ] Create donation soft credits

**Comment by samanthashain** [comment]
@allisonletts would you expect to also see contact affiliations and donation soft credits with corporate donation records (for the purpose of this recipe)?

**Comment by allisonletts** [comment]
Added!
